name: Deploy Docsify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Docsify CLI (optional)
        run: npm i -g docsify-cli

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: docs.scpslgame.cn
          commit_message: "Deploy Docsify [skip ci]"
          artifact_name: "docsify-pages-${{ github.run_id }}"
